### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by pepper-jk** [pepper-jk/dotfiles#10]
- [ ] still use the old 32 images, if rescanning the picture folder, because of a deviant amount of images.
- [ ] look into stdout instead of saving images!
- [ ] add fading animation while switching wallpaper [may dumb this]
